// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.1
// source: UserManager.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Gender int32

const (
	Gender_MALE   Gender = 0
	Gender_FEMALE Gender = 1
)

// Enum value maps for Gender.
var (
	Gender_name = map[int32]string{
		0: "MALE",
		1: "FEMALE",
	}
	Gender_value = map[string]int32{
		"MALE":   0,
		"FEMALE": 1,
	}
)

func (x Gender) Enum() *Gender {
	p := new(Gender)
	*p = x
	return p
}

func (x Gender) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Gender) Descriptor() protoreflect.EnumDescriptor {
	return file_UserManager_proto_enumTypes[0].Descriptor()
}

func (Gender) Type() protoreflect.EnumType {
	return &file_UserManager_proto_enumTypes[0]
}

func (x Gender) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Gender.Descriptor instead.
func (Gender) EnumDescriptor() ([]byte, []int) {
	return file_UserManager_proto_rawDescGZIP(), []int{0}
}

type SMSType int32

const (
	SMSType_REGISTER SMSType = 0
	SMSType_LOGIN    SMSType = 1
)

// Enum value maps for SMSType.
var (
	SMSType_name = map[int32]string{
		0: "REGISTER",
		1: "LOGIN",
	}
	SMSType_value = map[string]int32{
		"REGISTER": 0,
		"LOGIN":    1,
	}
)

func (x SMSType) Enum() *SMSType {
	p := new(SMSType)
	*p = x
	return p
}

func (x SMSType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SMSType) Descriptor() protoreflect.EnumDescriptor {
	return file_UserManager_proto_enumTypes[1].Descriptor()
}

func (SMSType) Type() protoreflect.EnumType {
	return &file_UserManager_proto_enumTypes[1]
}

func (x SMSType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SMSType.Descriptor instead.
func (SMSType) EnumDescriptor() ([]byte, []int) {
	return file_UserManager_proto_rawDescGZIP(), []int{1}
}

type GetUserInfoByIdRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetUserInfoByIdRequest) Reset() {
	*x = GetUserInfoByIdRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_UserManager_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUserInfoByIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserInfoByIdRequest) ProtoMessage() {}

func (x *GetUserInfoByIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_UserManager_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserInfoByIdRequest.ProtoReflect.Descriptor instead.
func (*GetUserInfoByIdRequest) Descriptor() ([]byte, []int) {
	return file_UserManager_proto_rawDescGZIP(), []int{0}
}

func (x *GetUserInfoByIdRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetUserInfoByIdResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Exist  bool   `protobuf:"varint,1,opt,name=exist,proto3" json:"exist,omitempty"`
	Name   string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Gender Gender `protobuf:"varint,3,opt,name=gender,proto3,enum=Gender" json:"gender,omitempty"`
}

func (x *GetUserInfoByIdResponse) Reset() {
	*x = GetUserInfoByIdResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_UserManager_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUserInfoByIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserInfoByIdResponse) ProtoMessage() {}

func (x *GetUserInfoByIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_UserManager_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserInfoByIdResponse.ProtoReflect.Descriptor instead.
func (*GetUserInfoByIdResponse) Descriptor() ([]byte, []int) {
	return file_UserManager_proto_rawDescGZIP(), []int{1}
}

func (x *GetUserInfoByIdResponse) GetExist() bool {
	if x != nil {
		return x.Exist
	}
	return false
}

func (x *GetUserInfoByIdResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetUserInfoByIdResponse) GetGender() Gender {
	if x != nil {
		return x.Gender
	}
	return Gender_MALE
}

type GetUserInfoByNumberRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Number string `protobuf:"bytes,1,opt,name=number,proto3" json:"number,omitempty"`
}

func (x *GetUserInfoByNumberRequest) Reset() {
	*x = GetUserInfoByNumberRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_UserManager_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUserInfoByNumberRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserInfoByNumberRequest) ProtoMessage() {}

func (x *GetUserInfoByNumberRequest) ProtoReflect() protoreflect.Message {
	mi := &file_UserManager_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserInfoByNumberRequest.ProtoReflect.Descriptor instead.
func (*GetUserInfoByNumberRequest) Descriptor() ([]byte, []int) {
	return file_UserManager_proto_rawDescGZIP(), []int{2}
}

func (x *GetUserInfoByNumberRequest) GetNumber() string {
	if x != nil {
		return x.Number
	}
	return ""
}

type GetUserInfoByNumberResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Exist  bool   `protobuf:"varint,1,opt,name=exist,proto3" json:"exist,omitempty"`
	Id     string `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Name   string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Gender Gender `protobuf:"varint,4,opt,name=gender,proto3,enum=Gender" json:"gender,omitempty"`
}

func (x *GetUserInfoByNumberResponse) Reset() {
	*x = GetUserInfoByNumberResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_UserManager_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUserInfoByNumberResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserInfoByNumberResponse) ProtoMessage() {}

func (x *GetUserInfoByNumberResponse) ProtoReflect() protoreflect.Message {
	mi := &file_UserManager_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserInfoByNumberResponse.ProtoReflect.Descriptor instead.
func (*GetUserInfoByNumberResponse) Descriptor() ([]byte, []int) {
	return file_UserManager_proto_rawDescGZIP(), []int{3}
}

func (x *GetUserInfoByNumberResponse) GetExist() bool {
	if x != nil {
		return x.Exist
	}
	return false
}

func (x *GetUserInfoByNumberResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetUserInfoByNumberResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetUserInfoByNumberResponse) GetGender() Gender {
	if x != nil {
		return x.Gender
	}
	return Gender_MALE
}

type LoginWithPasswordRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Number   string `protobuf:"bytes,1,opt,name=number,proto3" json:"number,omitempty"`
	Password string `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
}

func (x *LoginWithPasswordRequest) Reset() {
	*x = LoginWithPasswordRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_UserManager_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LoginWithPasswordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginWithPasswordRequest) ProtoMessage() {}

func (x *LoginWithPasswordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_UserManager_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginWithPasswordRequest.ProtoReflect.Descriptor instead.
func (*LoginWithPasswordRequest) Descriptor() ([]byte, []int) {
	return file_UserManager_proto_rawDescGZIP(), []int{4}
}

func (x *LoginWithPasswordRequest) GetNumber() string {
	if x != nil {
		return x.Number
	}
	return ""
}

func (x *LoginWithPasswordRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type LoginWithPasswordResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Succeed bool   `protobuf:"varint,1,opt,name=succeed,proto3" json:"succeed,omitempty"`
	Id      string `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *LoginWithPasswordResponse) Reset() {
	*x = LoginWithPasswordResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_UserManager_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LoginWithPasswordResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginWithPasswordResponse) ProtoMessage() {}

func (x *LoginWithPasswordResponse) ProtoReflect() protoreflect.Message {
	mi := &file_UserManager_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginWithPasswordResponse.ProtoReflect.Descriptor instead.
func (*LoginWithPasswordResponse) Descriptor() ([]byte, []int) {
	return file_UserManager_proto_rawDescGZIP(), []int{5}
}

func (x *LoginWithPasswordResponse) GetSucceed() bool {
	if x != nil {
		return x.Succeed
	}
	return false
}

func (x *LoginWithPasswordResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type LoginWithSMSRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Number string `protobuf:"bytes,1,opt,name=number,proto3" json:"number,omitempty"`
}

func (x *LoginWithSMSRequest) Reset() {
	*x = LoginWithSMSRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_UserManager_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LoginWithSMSRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginWithSMSRequest) ProtoMessage() {}

func (x *LoginWithSMSRequest) ProtoReflect() protoreflect.Message {
	mi := &file_UserManager_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginWithSMSRequest.ProtoReflect.Descriptor instead.
func (*LoginWithSMSRequest) Descriptor() ([]byte, []int) {
	return file_UserManager_proto_rawDescGZIP(), []int{6}
}

func (x *LoginWithSMSRequest) GetNumber() string {
	if x != nil {
		return x.Number
	}
	return ""
}

type LoginWithSMSResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Succeed bool   `protobuf:"varint,1,opt,name=succeed,proto3" json:"succeed,omitempty"`
	Id      string `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *LoginWithSMSResponse) Reset() {
	*x = LoginWithSMSResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_UserManager_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LoginWithSMSResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginWithSMSResponse) ProtoMessage() {}

func (x *LoginWithSMSResponse) ProtoReflect() protoreflect.Message {
	mi := &file_UserManager_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginWithSMSResponse.ProtoReflect.Descriptor instead.
func (*LoginWithSMSResponse) Descriptor() ([]byte, []int) {
	return file_UserManager_proto_rawDescGZIP(), []int{7}
}

func (x *LoginWithSMSResponse) GetSucceed() bool {
	if x != nil {
		return x.Succeed
	}
	return false
}

func (x *LoginWithSMSResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ChangeUserNameRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id      string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	NewName string `protobuf:"bytes,2,opt,name=newName,proto3" json:"newName,omitempty"`
}

func (x *ChangeUserNameRequest) Reset() {
	*x = ChangeUserNameRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_UserManager_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChangeUserNameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeUserNameRequest) ProtoMessage() {}

func (x *ChangeUserNameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_UserManager_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeUserNameRequest.ProtoReflect.Descriptor instead.
func (*ChangeUserNameRequest) Descriptor() ([]byte, []int) {
	return file_UserManager_proto_rawDescGZIP(), []int{8}
}

func (x *ChangeUserNameRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ChangeUserNameRequest) GetNewName() string {
	if x != nil {
		return x.NewName
	}
	return ""
}

type ChangeUserNameResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Succeed bool `protobuf:"varint,1,opt,name=succeed,proto3" json:"succeed,omitempty"`
}

func (x *ChangeUserNameResponse) Reset() {
	*x = ChangeUserNameResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_UserManager_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChangeUserNameResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeUserNameResponse) ProtoMessage() {}

func (x *ChangeUserNameResponse) ProtoReflect() protoreflect.Message {
	mi := &file_UserManager_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeUserNameResponse.ProtoReflect.Descriptor instead.
func (*ChangeUserNameResponse) Descriptor() ([]byte, []int) {
	return file_UserManager_proto_rawDescGZIP(), []int{9}
}

func (x *ChangeUserNameResponse) GetSucceed() bool {
	if x != nil {
		return x.Succeed
	}
	return false
}

type ChangeUserGenderRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	NewGender Gender `protobuf:"varint,2,opt,name=newGender,proto3,enum=Gender" json:"newGender,omitempty"`
}

func (x *ChangeUserGenderRequest) Reset() {
	*x = ChangeUserGenderRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_UserManager_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChangeUserGenderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeUserGenderRequest) ProtoMessage() {}

func (x *ChangeUserGenderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_UserManager_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeUserGenderRequest.ProtoReflect.Descriptor instead.
func (*ChangeUserGenderRequest) Descriptor() ([]byte, []int) {
	return file_UserManager_proto_rawDescGZIP(), []int{10}
}

func (x *ChangeUserGenderRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ChangeUserGenderRequest) GetNewGender() Gender {
	if x != nil {
		return x.NewGender
	}
	return Gender_MALE
}

type ChangeUserGenderResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Succeed bool `protobuf:"varint,1,opt,name=succeed,proto3" json:"succeed,omitempty"`
}

func (x *ChangeUserGenderResponse) Reset() {
	*x = ChangeUserGenderResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_UserManager_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChangeUserGenderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeUserGenderResponse) ProtoMessage() {}

func (x *ChangeUserGenderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_UserManager_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeUserGenderResponse.ProtoReflect.Descriptor instead.
func (*ChangeUserGenderResponse) Descriptor() ([]byte, []int) {
	return file_UserManager_proto_rawDescGZIP(), []int{11}
}

func (x *ChangeUserGenderResponse) GetSucceed() bool {
	if x != nil {
		return x.Succeed
	}
	return false
}

type RegisterRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Number   string `protobuf:"bytes,1,opt,name=number,proto3" json:"number,omitempty"`
	Password string `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Name     string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Id       string `protobuf:"bytes,4,opt,name=id,proto3" json:"id,omitempty"`
	Gender   Gender `protobuf:"varint,5,opt,name=gender,proto3,enum=Gender" json:"gender,omitempty"`
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_UserManager_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_UserManager_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_UserManager_proto_rawDescGZIP(), []int{12}
}

func (x *RegisterRequest) GetNumber() string {
	if x != nil {
		return x.Number
	}
	return ""
}

func (x *RegisterRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *RegisterRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RegisterRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RegisterRequest) GetGender() Gender {
	if x != nil {
		return x.Gender
	}
	return Gender_MALE
}

type RegisterResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IdCheck     bool `protobuf:"varint,1,opt,name=idCheck,proto3" json:"idCheck,omitempty"`
	NumberCheck bool `protobuf:"varint,2,opt,name=numberCheck,proto3" json:"numberCheck,omitempty"`
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_UserManager_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_UserManager_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_UserManager_proto_rawDescGZIP(), []int{13}
}

func (x *RegisterResponse) GetIdCheck() bool {
	if x != nil {
		return x.IdCheck
	}
	return false
}

func (x *RegisterResponse) GetNumberCheck() bool {
	if x != nil {
		return x.NumberCheck
	}
	return false
}

type RequestSMSRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Number string  `protobuf:"bytes,1,opt,name=number,proto3" json:"number,omitempty"`
	Type   SMSType `protobuf:"varint,2,opt,name=type,proto3,enum=SMSType" json:"type,omitempty"`
}

func (x *RequestSMSRequest) Reset() {
	*x = RequestSMSRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_UserManager_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RequestSMSRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestSMSRequest) ProtoMessage() {}

func (x *RequestSMSRequest) ProtoReflect() protoreflect.Message {
	mi := &file_UserManager_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestSMSRequest.ProtoReflect.Descriptor instead.
func (*RequestSMSRequest) Descriptor() ([]byte, []int) {
	return file_UserManager_proto_rawDescGZIP(), []int{14}
}

func (x *RequestSMSRequest) GetNumber() string {
	if x != nil {
		return x.Number
	}
	return ""
}

func (x *RequestSMSRequest) GetType() SMSType {
	if x != nil {
		return x.Type
	}
	return SMSType_REGISTER
}

type RequestSMSResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code         string `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	ValidMinutes int32  `protobuf:"varint,2,opt,name=validMinutes,proto3" json:"validMinutes,omitempty"`
}

func (x *RequestSMSResponse) Reset() {
	*x = RequestSMSResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_UserManager_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RequestSMSResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestSMSResponse) ProtoMessage() {}

func (x *RequestSMSResponse) ProtoReflect() protoreflect.Message {
	mi := &file_UserManager_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestSMSResponse.ProtoReflect.Descriptor instead.
func (*RequestSMSResponse) Descriptor() ([]byte, []int) {
	return file_UserManager_proto_rawDescGZIP(), []int{15}
}

func (x *RequestSMSResponse) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *RequestSMSResponse) GetValidMinutes() int32 {
	if x != nil {
		return x.ValidMinutes
	}
	return 0
}

var File_UserManager_proto protoreflect.FileDescriptor

var file_UserManager_proto_rawDesc = []byte{
	0x0a, 0x11, 0x55, 0x73, 0x65, 0x72, 0x4d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0x28, 0x0a, 0x16, 0x67, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x49, 0x6e,
	0x66, 0x6f, 0x42, 0x79, 0x49, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x64, 0x0a,
	0x17, 0x67, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x42, 0x79, 0x49, 0x64,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x78, 0x69, 0x73,
	0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x65, 0x78, 0x69, 0x73, 0x74, 0x12, 0x12,
	0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x12, 0x1f, 0x0a, 0x06, 0x67, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0e, 0x32, 0x07, 0x2e, 0x47, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x52, 0x06, 0x67, 0x65, 0x6e,
	0x64, 0x65, 0x72, 0x22, 0x34, 0x0a, 0x1a, 0x67, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x49, 0x6e,
	0x66, 0x6f, 0x42, 0x79, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x16, 0x0a, 0x06, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x22, 0x78, 0x0a, 0x1b, 0x67, 0x65, 0x74,
	0x55, 0x73, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x42, 0x79, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x78, 0x69, 0x73,
	0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x65, 0x78, 0x69, 0x73, 0x74, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12,
	0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x12, 0x1f, 0x0a, 0x06, 0x67, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x0e, 0x32, 0x07, 0x2e, 0x47, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x52, 0x06, 0x67, 0x65, 0x6e,
	0x64, 0x65, 0x72, 0x22, 0x4e, 0x0a, 0x18, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x57, 0x69, 0x74, 0x68,
	0x50, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x16, 0x0a, 0x06, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77,
	0x6f, 0x72, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77,
	0x6f, 0x72, 0x64, 0x22, 0x45, 0x0a, 0x19, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x57, 0x69, 0x74, 0x68,
	0x50, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x65, 0x64, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x2d, 0x0a, 0x13, 0x6c, 0x6f,
	0x67, 0x69, 0x6e, 0x57, 0x69, 0x74, 0x68, 0x53, 0x4d, 0x53, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x16, 0x0a, 0x06, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x22, 0x40, 0x0a, 0x14, 0x6c, 0x6f, 0x67,
	0x69, 0x6e, 0x57, 0x69, 0x74, 0x68, 0x53, 0x4d, 0x53, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x65, 0x64, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x41, 0x0a, 0x15, 0x63,
	0x68, 0x61, 0x6e, 0x67, 0x65, 0x55, 0x73, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x02, 0x69, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x6e, 0x65, 0x77, 0x4e, 0x61, 0x6d, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6e, 0x65, 0x77, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x32,
	0x0a, 0x16, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x55, 0x73, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63,
	0x65, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65,
	0x65, 0x64, 0x22, 0x50, 0x0a, 0x17, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x55, 0x73, 0x65, 0x72,
	0x47, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x25, 0x0a,
	0x09, 0x6e, 0x65, 0x77, 0x47, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e,
	0x32, 0x07, 0x2e, 0x47, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x52, 0x09, 0x6e, 0x65, 0x77, 0x47, 0x65,
	0x6e, 0x64, 0x65, 0x72, 0x22, 0x34, 0x0a, 0x18, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x55, 0x73,
	0x65, 0x72, 0x47, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x65, 0x64, 0x22, 0x8a, 0x01, 0x0a, 0x0f, 0x72,
	0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16,
	0x0a, 0x06, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f,
	0x72, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f,
	0x72, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1f, 0x0a, 0x06, 0x67, 0x65, 0x6e, 0x64, 0x65, 0x72,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x07, 0x2e, 0x47, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x52,
	0x06, 0x67, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x22, 0x4e, 0x0a, 0x10, 0x72, 0x65, 0x67, 0x69, 0x73,
	0x74, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x69,
	0x64, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x69, 0x64,
	0x43, 0x68, 0x65, 0x63, 0x6b, 0x12, 0x20, 0x0a, 0x0b, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x43,
	0x68, 0x65, 0x63, 0x6b, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0b, 0x6e, 0x75, 0x6d, 0x62,
	0x65, 0x72, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x22, 0x49, 0x0a, 0x11, 0x72, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x53, 0x4d, 0x53, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06,
	0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6e, 0x75,
	0x6d, 0x62, 0x65, 0x72, 0x12, 0x1c, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0e, 0x32, 0x08, 0x2e, 0x53, 0x4d, 0x53, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79,
	0x70, 0x65, 0x22, 0x4c, 0x0a, 0x12, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x53, 0x4d, 0x53,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x22, 0x0a, 0x0c,
	0x76, 0x61, 0x6c, 0x69, 0x64, 0x4d, 0x69, 0x6e, 0x75, 0x74, 0x65, 0x73, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x0c, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x4d, 0x69, 0x6e, 0x75, 0x74, 0x65, 0x73,
	0x2a, 0x1e, 0x0a, 0x06, 0x47, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x12, 0x08, 0x0a, 0x04, 0x4d, 0x41,
	0x4c, 0x45, 0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06, 0x46, 0x45, 0x4d, 0x41, 0x4c, 0x45, 0x10, 0x01,
	0x2a, 0x22, 0x0a, 0x07, 0x53, 0x4d, 0x53, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0c, 0x0a, 0x08, 0x52,
	0x45, 0x47, 0x49, 0x53, 0x54, 0x45, 0x52, 0x10, 0x00, 0x12, 0x09, 0x0a, 0x05, 0x4c, 0x4f, 0x47,
	0x49, 0x4e, 0x10, 0x01, 0x32, 0xb2, 0x04, 0x0a, 0x0b, 0x55, 0x73, 0x65, 0x72, 0x4d, 0x61, 0x6e,
	0x61, 0x67, 0x65, 0x72, 0x12, 0x46, 0x0a, 0x0f, 0x67, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x49,
	0x6e, 0x66, 0x6f, 0x42, 0x79, 0x49, 0x64, 0x12, 0x17, 0x2e, 0x67, 0x65, 0x74, 0x55, 0x73, 0x65,
	0x72, 0x49, 0x6e, 0x66, 0x6f, 0x42, 0x79, 0x49, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x18, 0x2e, 0x67, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x42, 0x79,
	0x49, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x52, 0x0a, 0x13,
	0x67, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x42, 0x79, 0x4e, 0x75, 0x6d,
	0x62, 0x65, 0x72, 0x12, 0x1b, 0x2e, 0x67, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x49, 0x6e, 0x66,
	0x6f, 0x42, 0x79, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x1c, 0x2e, 0x67, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x42, 0x79,
	0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00,
	0x12, 0x4c, 0x0a, 0x11, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x57, 0x69, 0x74, 0x68, 0x50, 0x61, 0x73,
	0x73, 0x77, 0x6f, 0x72, 0x64, 0x12, 0x19, 0x2e, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x57, 0x69, 0x74,
	0x68, 0x50, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x1a, 0x2e, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x57, 0x69, 0x74, 0x68, 0x50, 0x61, 0x73, 0x73,
	0x77, 0x6f, 0x72, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x3d,
	0x0a, 0x0c, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x57, 0x69, 0x74, 0x68, 0x53, 0x4d, 0x53, 0x12, 0x14,
	0x2e, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x57, 0x69, 0x74, 0x68, 0x53, 0x4d, 0x53, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x15, 0x2e, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x57, 0x69, 0x74, 0x68,
	0x53, 0x4d, 0x53, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x43, 0x0a,
	0x0e, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x55, 0x73, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x12,
	0x16, 0x2e, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x55, 0x73, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65,
	0x55, 0x73, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x00, 0x12, 0x49, 0x0a, 0x10, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x55, 0x73, 0x65, 0x72,
	0x47, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x12, 0x18, 0x2e, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x55,
	0x73, 0x65, 0x72, 0x47, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x19, 0x2e, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x55, 0x73, 0x65, 0x72, 0x47, 0x65, 0x6e,
	0x64, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x31, 0x0a,
	0x08, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x12, 0x10, 0x2e, 0x72, 0x65, 0x67, 0x69,
	0x73, 0x74, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x11, 0x2e, 0x72, 0x65,
	0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00,
	0x12, 0x37, 0x0a, 0x0a, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x53, 0x4d, 0x53, 0x12, 0x12,
	0x2e, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x53, 0x4d, 0x53, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x13, 0x2e, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x53, 0x4d, 0x53, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x09, 0x5a, 0x07, 0x2e, 0x2f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_UserManager_proto_rawDescOnce sync.Once
	file_UserManager_proto_rawDescData = file_UserManager_proto_rawDesc
)

func file_UserManager_proto_rawDescGZIP() []byte {
	file_UserManager_proto_rawDescOnce.Do(func() {
		file_UserManager_proto_rawDescData = protoimpl.X.CompressGZIP(file_UserManager_proto_rawDescData)
	})
	return file_UserManager_proto_rawDescData
}

var file_UserManager_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_UserManager_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_UserManager_proto_goTypes = []interface{}{
	(Gender)(0),                         // 0: Gender
	(SMSType)(0),                        // 1: SMSType
	(*GetUserInfoByIdRequest)(nil),      // 2: getUserInfoByIdRequest
	(*GetUserInfoByIdResponse)(nil),     // 3: getUserInfoByIdResponse
	(*GetUserInfoByNumberRequest)(nil),  // 4: getUserInfoByNumberRequest
	(*GetUserInfoByNumberResponse)(nil), // 5: getUserInfoByNumberResponse
	(*LoginWithPasswordRequest)(nil),    // 6: loginWithPasswordRequest
	(*LoginWithPasswordResponse)(nil),   // 7: loginWithPasswordResponse
	(*LoginWithSMSRequest)(nil),         // 8: loginWithSMSRequest
	(*LoginWithSMSResponse)(nil),        // 9: loginWithSMSResponse
	(*ChangeUserNameRequest)(nil),       // 10: changeUserNameRequest
	(*ChangeUserNameResponse)(nil),      // 11: changeUserNameResponse
	(*ChangeUserGenderRequest)(nil),     // 12: changeUserGenderRequest
	(*ChangeUserGenderResponse)(nil),    // 13: changeUserGenderResponse
	(*RegisterRequest)(nil),             // 14: registerRequest
	(*RegisterResponse)(nil),            // 15: registerResponse
	(*RequestSMSRequest)(nil),           // 16: requestSMSRequest
	(*RequestSMSResponse)(nil),          // 17: requestSMSResponse
}
var file_UserManager_proto_depIdxs = []int32{
	0,  // 0: getUserInfoByIdResponse.gender:type_name -> Gender
	0,  // 1: getUserInfoByNumberResponse.gender:type_name -> Gender
	0,  // 2: changeUserGenderRequest.newGender:type_name -> Gender
	0,  // 3: registerRequest.gender:type_name -> Gender
	1,  // 4: requestSMSRequest.type:type_name -> SMSType
	2,  // 5: UserManager.getUserInfoById:input_type -> getUserInfoByIdRequest
	4,  // 6: UserManager.getUserInfoByNumber:input_type -> getUserInfoByNumberRequest
	6,  // 7: UserManager.loginWithPassword:input_type -> loginWithPasswordRequest
	8,  // 8: UserManager.loginWithSMS:input_type -> loginWithSMSRequest
	10, // 9: UserManager.changeUserName:input_type -> changeUserNameRequest
	12, // 10: UserManager.changeUserGender:input_type -> changeUserGenderRequest
	14, // 11: UserManager.register:input_type -> registerRequest
	16, // 12: UserManager.requestSMS:input_type -> requestSMSRequest
	3,  // 13: UserManager.getUserInfoById:output_type -> getUserInfoByIdResponse
	5,  // 14: UserManager.getUserInfoByNumber:output_type -> getUserInfoByNumberResponse
	7,  // 15: UserManager.loginWithPassword:output_type -> loginWithPasswordResponse
	9,  // 16: UserManager.loginWithSMS:output_type -> loginWithSMSResponse
	11, // 17: UserManager.changeUserName:output_type -> changeUserNameResponse
	13, // 18: UserManager.changeUserGender:output_type -> changeUserGenderResponse
	15, // 19: UserManager.register:output_type -> registerResponse
	17, // 20: UserManager.requestSMS:output_type -> requestSMSResponse
	13, // [13:21] is the sub-list for method output_type
	5,  // [5:13] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_UserManager_proto_init() }
func file_UserManager_proto_init() {
	if File_UserManager_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_UserManager_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetUserInfoByIdRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_UserManager_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetUserInfoByIdResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_UserManager_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetUserInfoByNumberRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_UserManager_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetUserInfoByNumberResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_UserManager_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LoginWithPasswordRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_UserManager_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LoginWithPasswordResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_UserManager_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LoginWithSMSRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_UserManager_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LoginWithSMSResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_UserManager_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChangeUserNameRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_UserManager_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChangeUserNameResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_UserManager_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChangeUserGenderRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_UserManager_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChangeUserGenderResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_UserManager_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegisterRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_UserManager_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegisterResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_UserManager_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RequestSMSRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_UserManager_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RequestSMSResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_UserManager_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_UserManager_proto_goTypes,
		DependencyIndexes: file_UserManager_proto_depIdxs,
		EnumInfos:         file_UserManager_proto_enumTypes,
		MessageInfos:      file_UserManager_proto_msgTypes,
	}.Build()
	File_UserManager_proto = out.File
	file_UserManager_proto_rawDesc = nil
	file_UserManager_proto_goTypes = nil
	file_UserManager_proto_depIdxs = nil
}
